PACKET_SIZE = 512
RECEIVER_ADDR = ('localhost', 4040)
SENDER_ADDR = ('localhost', 0)
SLEEP_INTERVAL = 0.05
TIMEOUT_INTERVAL = 0.5
DROP_PACKET_PROB = 8
DROP_PACKET_CHECKSUM = 8
SIZE_RANDOM_FILENAME = 7